spring.application.name=api

#   Conex�o Com banco de dados
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/arcana_web
spring.datasource.username=root
spring.datasource.password=root

#   Dizer pro JPA para n�o criar tabelas no BD e sim validar com o FLyway
spring.jpa.hibernate.ddl-auto=validate 
#   Mostra as queries SQL no console q foram executadas
spring.jpa.show-sql=true


#Ativa o Flyway e diz aonde est�o os arquivos .sql
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration